### ISSUE TITLE
Listener error

### ISSUE THREAD

**Issue by d0ubl3puls4r** [Souhardya/Zerodoor#5]
Hello, I was able to receive the reverse connection of the server when it was executed, but I immediately received an error, as I show below:

~ A Simple Listener To Accept Connections From Compromised Hosts ~

Please specify the port: 443
Binding socket to port: 443
Connection has been established | IP 192.168.1.10 | Port 49352

Traceback (most recent call last):
  File "./zerodoor.py", line 328, in <module>
    main ()
  File "./zerodoor.py", line 53, in main
    socket_accept ()
  File "./zerodoor.py", line 311, in socket_accept
    send_commands (conn)
  File "./zerodoor.py", line 317, in send_commands
    cmd = input ()
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by Souhardya** [comment]
Now please kindly check :) if you got any error please reopen the issue closing it for now
